### ISSUE TITLE
Images not working

### ISSUE THREAD

**Issue by MrPigeontheCoder** [win93-community/windows93-docs#12] opened 2022-11-17 15:28 UTC
Ok so the images are not loading properly...
![image](https://user-images.githubusercontent.com/105377999/202486598-f0db915f-33f1-4809-998e-4ad376708a17.png)

And this is the code
![image](https://user-images.githubusercontent.com/105377999/202486923-c67f365a-d2ca-48b7-a7e2-4c3a24ef505d.png)
we need to fix this.

Also, using permalinks does NOT work
![image](https://user-images.githubusercontent.com/105377999/202487461-0a4964d1-7213-49bd-9e1b-bbd07350166a.png)
![image](https://user-images.githubusercontent.com/105377999/202487539-f2311b70-bafa-4da7-9b71-e8b5236c5319.png)

We also need to get those white table thingies under control. 

I'm trying to work on it right now, but feel free to help out

**Comment by stretch07** [comment] 2022-11-17 19:04
i've been investigating the images for a while now. I believe the cause is docsify's linking system
perhaps we should just put in a :ignore tag after it? - https://docsify.js.org/#/helpers?id=ignore-to-compile-link
the white thing on the tables is driving me nuts, it appears to be a theming issue. I really don't want to mess with the themes, so I'm about to open up an issue in the docsifyjs repo

**Comment by stretch07** [comment] 2022-11-17 19:12
Issue created: https://github.com/docsifyjs/docsify/issues/1927

**Comment by MrPigeontheCoder** [comment] 2022-11-18 08:30
> i've been investigating the images for a while now. I believe the cause is docsify's linking system perhaps we should just put in a :ignore tag after it? - https://docsify.js.org/#/helpers?id=ignore-to-compile-link the white thing on the tables is driving me nuts, it appears to be a theming issue. I really don't want to mess with the themes, so I'm about to open up an issue in the docsifyjs repo

Ok, i'll add the ignore tag

**Comment by stretch07** [comment] 2022-11-18 16:18
Alright, let's see if that works! Either way we should look at examples of how other documwntations add images; perhaps that will point out to us what we're missing😅
Btw someone from docsify has fixed the table row issue and is going to merge their PR, so I hope it will be fixed soon!

**Comment by MrPigeontheCoder** [comment] 2022-11-18 16:18
ok, cool

**Comment by MrPigeontheCoder** [comment] 2022-11-18 16:22
> Alright, let's see if that works! Either way we should look at examples of how other documwntations add images; perhaps that will point out to us what we're missing😅 Btw someone from docsify has fixed the table row issue and is going to merge their PR, so I hope it will be fixed soon!

also, I'm going to start working on a virus, i might publish it once i'm done...

**Comment by MrPigeontheCoder** [comment] 2022-11-21 16:58
So i was thinking: What if we use a codespace to test changes BEFORE pushing?

**Comment by stretch07** [comment] 2022-11-22 02:13
Awesome idea! I'm unfamiliar with codespaces as they just came out of beta but I think I'll get the gist of it 👍 
I'll be updating the style guide soon as well, that way we can have that reference as well.

**Comment by MrPigeontheCoder** [comment] 2022-11-25 21:15
> Awesome idea! I'm unfamiliar with codespaces as they just came out of beta but I think I'll get the gist of it 👍 I'll be updating the style guide soon as well, that way we can have that reference as well.

AFAIK, they act as an online VM, that can host webpages as well. We could probs host the website there, and maybe, just in case something goes wrong, we could create another account. We could also do that to get more codespace hours.

**Comment by stretch07** [comment] 2022-11-27 23:59
The table issue is fixed, it should be pushed to npm and cdnjs and all the package managers soon. I still have no idea what is causing the image issue

**Comment by MrPigeontheCoder** [comment] 2022-11-28 07:10
> The table issue is fixed, it should be pushed to npm and cdnjs and all the package managers soon. I still have no idea what is causing this

Perfect! If I make any more changes, I'll test them either in a fork or a codespace BEFORE merging, and then I'll send you the results

**Comment by stretch07** [comment] 2022-11-29 02:43
Nice. Also if you're certain it works you're allowed to push it
key things are: 
a) same style as the rest of the docs
b) no bugs!

**Comment by MrPigeontheCoder** [comment] 2022-11-29 14:03
Ok, i also saw your little message on the org page. I'll make sure to follow that

**Comment by stretch07** [comment] 2023-10-17 04:41
its been a year, reopen if this is still happening

**Closed as not planned by stretch07** 2023-10-17 04:41 UTC
Labels: bug
